/**
 * Healthcare Output Sanitizer Utility
 * Processes raw LLM backend responses, extracted PDF text, and API outputs:
 * 1. Strips robotic AI clutter, confidence scores, and meta disclaimers.
 * 2. Cleans rogue apostrophes, escaped quotes, raw backticks, and extra whitespace.
 * 3. Safely parses stringified JSON blocks into structured data objects for visual UI card rendering.
 * 4. Parses markdown structures (lists, key-values, headers) into sanitized render blocks.
 */

export interface SanitizedBlock {
  type: 'header' | 'list' | 'kv' | 'paragraph' | 'divider' | 'callout' | 'table';
  level?: number;
  title?: string;
  items?: string[];
  key?: string;
  value?: string;
  text?: string;
  rows?: Array<Record<string, string>>;
  variant?: 'info' | 'warning' | 'success';
}

export interface SanitizedOutputResult {
  isJson: boolean;
  jsonData: any | null;
  rawText: string;
  cleanText: string;
  blocks: SanitizedBlock[];
}

// Patterns of robotic AI phrases & confidence markers to strip
const ROBOTIC_CLUTTER_PATTERNS = [
  /Based on the provided PDF(?: document| report| data| text)?,?\s*/gi,
  /Based on the clinical notes provided,?\s*/gi,
  /As an AI language model,?\s*/gi,
  /As an AI medical assistant,?\s*/gi,
  /AI Confidence:\s*\d+(?:\.\d+)?%?\s*/gi,
  /Confidence score:\s*\d+(?:\.\d+)?%?\s*/gi,
  /Confidence:\s*\d+(?:\.\d+)?%?\s*/gi,
  /\bScore:\s*0\.\d+\b/gi,
  /Disclaimer:\s*I am an AI assistant and not a licensed physician\.\s*/gi,
  /AI Generated Output:\s*/gi,
  /Model Output:\s*/gi,
  /Note: This information is generated by an artificial intelligence model\.\s*/gi,
];

/**
 * Main sanitization function
 */
export function sanitizeHealthcareOutput(input: any): SanitizedOutputResult {
  if (input === null || input === undefined) {
    return { isJson: false, jsonData: null, rawText: '', cleanText: '', blocks: [] };
  }

  let text = typeof input === 'string' ? input : JSON.stringify(input, null, 2);
  const originalText = text;

  // 1. Check if the string is stringified JSON or JSON wrapped in markdown code fence
  let jsonParsed: any = null;
  let isJson = false;

  // Attempt direct JSON parse
  let jsonCandidate = text.trim();
  if (jsonCandidate.startsWith('```json')) {
    jsonCandidate = jsonCandidate.replace(/^```json\s*/i, '').replace(/\s*```$/, '');
  } else if (jsonCandidate.startsWith('```')) {
    jsonCandidate = jsonCandidate.replace(/^```\s*/, '').replace(/\s*```$/, '');
  }

  if (
    (jsonCandidate.startsWith('{') && jsonCandidate.endsWith('}')) ||
    (jsonCandidate.startsWith('[') && jsonCandidate.endsWith(']'))
  ) {
    try {
      jsonParsed = JSON.parse(jsonCandidate);
      isJson = true;
    } catch {
      isJson = false;
    }
  }

  if (isJson && jsonParsed) {
    return {
      isJson: true,
      jsonData: jsonParsed,
      rawText: originalText,
      cleanText: JSON.stringify(jsonParsed, null, 2),
      blocks: [],
    };
  }

  // 2. Strip AI Robotic Clutter
  let cleaned = text;
  for (const pattern of ROBOTIC_CLUTTER_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }

  // 3. Format Cleanup
  // Remove markdown code wrappers if present without JSON
  cleaned = cleaned.replace(/^```[a-z]*\n?/gi, '').replace(/\n?```$/gi, '');

  // Unescape backslash quotes
  cleaned = cleaned.replace(/\\"/g, '"').replace(/\\'/g, "'");

  // Trim stray leading/trailing quotes and apostrophes
  cleaned = cleaned.replace(/^['"]+|['"]+$/g, '');

  // Normalize rogue backticks
  cleaned = cleaned.replace(/`{2,}/g, '`');

  // Replace 3+ consecutive newlines with double newline
  cleaned = cleaned.replace(/\r/g, '').replace(/\n{3,}/g, '\n\n');

  // Trim start & end whitespace
  cleaned = cleaned.trim();

  // 4. Structural Parsing into Render Blocks
  const blocks = parseStructuredBlocks(cleaned);

  return {
    isJson: false,
    jsonData: null,
    rawText: originalText,
    cleanText: cleaned,
    blocks,
  };
}

/**
 * Parses cleaned medical text into structured blocks (headers, lists, key-value grids, paragraphs, callouts)
 */
function parseStructuredBlocks(text: string): SanitizedBlock[] {
  if (!text) return [];

  const lines = text.split('\n');
  const blocks: SanitizedBlock[] = [];
  let currentList: string[] = [];
  let currentParagraphLines: string[] = [];

  const flushList = () => {
    if (currentList.length > 0) {
      blocks.push({ type: 'list', items: [...currentList] });
      currentList = [];
    }
  };

  const flushParagraph = () => {
    if (currentParagraphLines.length > 0) {
      const pText = currentParagraphLines.join(' ').trim();
      if (pText) {
        blocks.push({ type: 'paragraph', text: pText });
      }
      currentParagraphLines = [];
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    if (!line) {
      flushList();
      flushParagraph();
      continue;
    }

    // Horizontal Dividers
    if (/^(---|\*\*\*|___)$/.test(line)) {
      flushList();
      flushParagraph();
      blocks.push({ type: 'divider' });
      continue;
    }

    // Headers (# Header, ## Header, ### Header, or BOLD Header ending in colon)
    const headerMatch = line.match(/^(#{1,4})\s+(.+)$/);
    if (headerMatch) {
      flushList();
      flushParagraph();
      blocks.push({
        type: 'header',
        level: headerMatch[1].length,
        title: headerMatch[2].replace(/\*\*/g, '').trim(),
      });
      continue;
    }

    // Bold standalone section titles (e.g. "**DIAGNOSIS & IMPRESSION:**" or "**1. Patient Summary**")
    const standaloneBoldMatch = line.match(/^(?:(?:[*\-•]|\d+\.)\s+)?\*\*([^*]+)\*\*\s*:?\s*$/);
    if (standaloneBoldMatch) {
      flushList();
      flushParagraph();
      blocks.push({
        type: 'header',
        level: 3,
        title: standaloneBoldMatch[1].trim(),
      });
      continue;
    }

    if (/^[A-Z\s]{4,}:\s*$/.test(line)) {
      flushList();
      flushParagraph();
      blocks.push({
        type: 'header',
        level: 3,
        title: line.replace(/:$/, '').trim(),
      });
      continue;
    }

    // Key-Value pairs (e.g. "**Patient Name:** John Doe" or "Hemoglobin: 14.2 g/dL")
    // Allow optional leading bullet point or number
    const kvMatch = line.match(/^(?:(?:[*\-•]|\d+\.)\s+)?(?:\*\*)?([A-Za-z0-9\s/_-]{2,40})(?:\*\*)?:\s*(.+)$/);
    if (kvMatch) {
      // Check if value is short enough to be a KV pair vs a full paragraph
      const key = kvMatch[1].replace(/\*\*/g, '').trim();
      const val = kvMatch[2].trim();
      if (val.length < 150 && !val.includes('\n')) {
        flushList();
        flushParagraph();
        blocks.push({
          type: 'kv',
          key,
          value: val.replace(/\*\*/g, ''),
        });
        continue;
      }
    }

    // Bullet points (*, -, •, 1., 2.)
    const bulletMatch = line.match(/^([*\-•]|\d+\.)\s+(.+)$/);
    if (bulletMatch) {
      flushParagraph();
      currentList.push(bulletMatch[2].trim());
      continue;
    }

    // Callout boxes (e.g., Note:, Warning:, Critical:)
    const calloutMatch = line.match(/^(NOTE|WARNING|CRITICAL|RECOMMENDATION|ALERT):\s*(.+)$/i);
    if (calloutMatch) {
      flushList();
      flushParagraph();
      const tag = calloutMatch[1].toUpperCase();
      let variant: 'info' | 'warning' | 'success' = 'info';
      if (tag === 'WARNING' || tag === 'CRITICAL' || tag === 'ALERT') variant = 'warning';
      if (tag === 'RECOMMENDATION') variant = 'success';

      blocks.push({
        type: 'callout',
        title: tag,
        text: calloutMatch[2].trim(),
        variant,
      });
      continue;
    }

    // Default paragraph line
    flushList();
    currentParagraphLines.push(line);
  }

  flushList();
  flushParagraph();

  return blocks;
}
